- type: gameMap
  id: Train
  mapName: 'Train'
  mapPath: /Maps/train.yml
  maxRandomOffset: 0
  randomRotation: false
  minPlayers: 35
  maxPlayers: 70
  stations:
    Train:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: 'Train "Sentipode" {0}-{1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'ED'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_omega.yml # TODO - add railway station
        - type: StationJobs
          availableJobs:
            #service
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            Bartender: [ 1, 1 ]
            Botanist: [ 2, 2 ]
            Chef: [ 1, 1 ]
            Janitor: [ 2, 2 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ 2, 3 ]
            Detective: [ 1, 1 ]
            #engineering
            ChiefEngineer: [ 1, 1 ]
            AtmosphericTechnician: [ 3, 3 ]
            StationEngineer: [ 5, 5 ]
            TechnicalAssistant: [ 3, 3 ]
            #medical
            ChiefMedicalOfficer: [ 1, 1 ]
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 2, 2 ]
            MedicalIntern: [ 2, 2 ]
            Paramedic: [ 1, 1 ]
            # MedicalSurgeon: [ 1, 1 ]
            #science
            ResearchDirector: [ 1, 1 ]
            Scientist: [ 4, 4 ]
            ResearchAssistant: [ 2, 2 ]
            #security
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 4, 4 ]
            SecurityCadet: [ 3, 3 ]
            #supply
            Quartermaster: [ 1, 1 ]
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 3, 3 ]
            #civilian
            Passenger: [ -1, -1 ]
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            # seniors
            SeniorEngineer: [1, 1 ]
            SeniorPhysician: [ 1, 1 ]
            SeniorResearcher: [ 1, 1 ]
            SeniorOfficer: [ 1, 1 ]
            SeniorSalvageSpecialist: [ 1, 1 ]
            SeniorAdministrator: [ 1, 1 ]
            # law
            # Magistrat: [ 1, 1 ]
            IAA: [ 1, 1 ]
            Lawyer: [ 2, 2 ]
            # silicon
            StationAi: [ 1, 1 ]
            Borg: [ 2, 2 ]
            BorgSecurity: [ 1, 1 ]
            # DS14
            BlueShieldOfficer: [ 1, 1 ]
            Brigmedic: [ 1, 1 ]
            ClownSponsor: [ 0, 2 ]
            Coroner: [ 1, 1 ]
            SecurityPilot: [ 1, 1 ]
