- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 # 30 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hours
    - !type:RoleTimeRequirement
      role: JobHeadOfPersonnel
      time: 18000 # 5 hours
    - !type:OverallPlaytimeRequirement
      time: 504000 # 140 hours
    - !type:AgeRequirement
      requiredAge: 26
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  #start-backmen: currency
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: Command
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
    socks: ClothingUnderwearSocksCaptain
  storage:
    back:
    - Flash
    # - StationCharter
