- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Science
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 # 10 hours
    - !type:OverallPlaytimeRequirement
      time: 216000 # 60 hours
    - !type:AgeRequirement
      requiredAge: 26
  weight: 15
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - SeniorSalvage
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  - Coroner
  - Paramedic
  - Brigmedic
  #start-backmen: currency
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: Command
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoPGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: HoPPDA
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
    socks: ClothingUnderwearSocksHeadofPersonnel
  storage:
    back:
    - Flash
