- type: job
  id: TypanRD
  name: job-name-typan-rd
  playTimeTracker: TypanRD
  description: Директор исследований из далёкого космоса.
  startingGear: SyndicateRD
  icon: "JobIconSyndicateRD"
  supervisors: job-supervisors-typan-syndicate
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 60000
    - !type:OverallPlaytimeRequirement
      time: 150000
    - !type:AgeRequirement
      requiredAge: 24
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess

- type: startingGear
  id: SyndicateRD
  equipment:
    eyes: ClothingEyesGlassesHiddenSecurity
    ears: ClothingHeadsetAltTypan
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterCoatRDTypan
    gloves: ClothingHandsRDTypan
    id: SyndiPDARD
    back: ClothingBackpackSyndicate
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    belt: ClothingBeltAssaultTypan
