- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 144000 # 40 hours
    - !type:OverallPlaytimeRequirement
      time: 360000 # 100 hours
    - !type:AgeRequirement
      requiredAge: 24
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Brigmedic
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: Command
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    socks: ClothingUnderwearSocksHeadOfSecurity
  storage:
    back:
    - Flash
    - HyperLinkBookCorporateLaw
    - HyperLinkBookSOPSecurity
