- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 21600 # 6 hours
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 7200 # 2 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 21600 # 6 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 216000 # 60 hours
    - !type:AgeRequirement
      requiredAge: 24
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Security
  wage: 75
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretSecurity
    ears: ClothingHeadsetSecurity
    pocket1: WeaponRevolverDeckard
    socks: ClothingUnderwearSocksSeniorOfficer
  storage:
    back:
    - Flash
    - SpeedLoaderMagnum
    - SpeedLoaderMagnum
    - SpeedLoaderMagnum
    - HyperLinkBookCorporateLaw
    - HyperLinkBookSOPSecurity
