- type: job
  id: CentralCommandOperator
  name: job-name-centcom-operator
  description: job-description-centcom-operator
  playTimeTracker: JobCentralCommandOperator
  setPreference: false
  startingGear: CentcomOperatorGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom-administrator
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentcomOperatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatCentcomcap
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    id: CentcomOperatorPDA
    ears: ClothingHeadsetCentCom
    neck: ClothingNeckTieDet
    belt: BoxFolderCentComClipboard
    pocket1: RubberStampCentcom
    pocket2: ClothingMaskGasCentcom
  #   underwearb: ClothingUnderwearBottomBoxersCentcomm # DS14-Underwear
  # underweart: ClothingUnderwearTopBraCentcomm # DS14-Underwear
  # underwearb: ClothingUnderwearBottomPantiesCentcomm # DS14-Underwear
  # innerClothingSkirt: ClothingUniformJumpskirtPencilCentcomOfficial
  # storage:
  #   back:
  #   - 
