- type: startingGear
  id: CentcomRepresentativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficer
    back: ClothingBackpackFilledCentcomRepresentative
    shoes: ClothingShoesBootsLaceup
    outerClothing: ClothingOuterVestWeb
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatBeretCentcomNaval
    id: CentcomPDA
    gloves: ClothingHandsGlovesColorGray
    ears: ClothingHeadsetCentCom
    pocket1: MacroBombImplanter
  #   underwearb: ClothingUnderwearBottomBoxersCentcomm # DS14-Underwear
  # underweart: ClothingUnderwearTopBraCentcomm # DS14-Underwear
  # underwearb: ClothingUnderwearBottomPantiesCentcomm # DS14-Underwear
  # innerClothingSkirt: ClothingUniformJumpskirtPencilCentcomOfficial

- type: entity
  parent: ClothingBackpack
  id: ClothingBackpackFilledCentcomRepresentative
  components:
  - type: StorageFill
    contents:
      - id: BoxSurvival
      - id: RubberStampCentcom
      - id: BoxFolderRedFilled

- type: entity
  parent: BoxFolderBase
  id: BoxFolderRedFilled
  suffix: Red
  name: папка с секретными документами
  description: Вам точно не следует знать что там написано. В любом случае, текст написан особыми невидимыми чернилами.
  components:
    - type: StorageFill
      contents:
      - id: Paper
        amount: 8
    - type: Sprite
      sprite: Objects/Misc/bureaucracy.rsi
      layers:
      - state: folder-colormap
        color: "#FF0000"
      - state: folder-base
