- type: startingGear
  id: CentcomSpaceNavyRepresentativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficer
    back: ClothingBackpackFilledSNR
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterVestWeb
    eyes: ClothingEyesGlassesSecurity
    id: CentcomPDA
    gloves: ClothingHandsGlovesColorWhite
    ears: ClothingHeadsetCentCom
    pocket1: MacroBombImplanter
  #   underwearb: ClothingUnderwearBottomBoxersWhite # DS14-Underwear
  # underweart: ClothingUnderwearTopBraWhite # DS14-Underwear
  # underwearb: ClothingUnderwearBottomPantiesWhite # DS14-Underwear

- type: entity
  parent: ClothingBackpack
  id: ClothingBackpackFilledSNR
  components:
  - type: StorageFill
    contents:
      - id: BoxSurvivalSecurity
      - id: RubberStampCentcom
      - id: BoxFolderWhiteFilled

- type: entity
  parent: BoxFolderBase
  id: BoxFolderWhiteFilled
  suffix: White
  name: папка с секретными документами
  description: Вам точно не следует знать что там написано. В любом случае, текст написан особыми невидимыми чернилами.
  components:
    - type: StorageFill
      contents:
      - id: Paper
        amount: 8
    - type: Sprite
      sprite: Objects/Misc/bureaucracy.rsi
      layers:
      - state: folder-colormap
        color: "#FFFFFF"
      - state: folder-base
