- type: gameMapPool
  id: DefaultMapPool
  maps:
  - CorvaxAstra
  - CorvaxAvrite
  - CorvaxDelta
  - CorvaxPaper
  - CorvaxSilly
  - CorvaxSpectrum
  - Amber
  - Aspid
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Convex
  - Core
  - Fland
  - Gemini
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Packed
  - Saltern
  - Train
  - Gate
  - Loop
  - Convex
  - Plasma
  - Cog