- type: gameMapPool
  id: DefaultMapPool
  maps:
  - CorvaxAstra
  - CorvaxAvrite
  - CorvaxDelta
  - CorvaxGate
  - CorvaxPaper
  - CorvaxSilly
  - CorvaxSpectrum
  - Aspid
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Core
  - Fland
  - Gemini
  - Marathon
  - Meta
  - Oasis
  # - Omega # Until fix
  - Origin
  - Packed
  - Saltern
  - Train
