- type: startingGear
  id: CluwneGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCluwne
    back: ClothingBackpackCluwne
    shoes: ClothingShoesCluwne
    mask: ClothingMaskCluwne
    id: CluwnePDA
    gloves: ClothingHandsGlovesCluwne
    pocket1: CluwneHorn
  #   underwearb: ClothingUnderwearBottomBoxersClown # DS14-Underwear
  # underweart: ClothingUnderwearTopBraClown # DS14-Underwear
  # underwearb: ClothingUnderwearBottomPantiesClown # DS14-Underwear

- type: startingGear
  id: HoloClownGear
  equipment:
    pocket1: BikeHorn

