- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#a46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - SeniorSalvageSpecialist
  accountNumber: 1315 #backmen: currency

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#6ca729"
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - ClownSponsor
  - SeniorAdministrator
  accountNumber: 1316 #backmen: currency

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  roles:
  - CentralCommandOfficial
  - CentralCommandAdministrator
  - CentralCommandOperator
  - CentralCommandSpecialOperationsOfficer
  - CentralCommandOfficer
  - CBURNLeader
  - CBURNSierraLeader
  - CBURNAgent
  - CBURNSierraAgent
  - ERTLeaderAmber
  - ERTLeaderRed
  - ERTLeaderGamma
  - ERTSecurityAmber
  - ERTSecurityRed
  - ERTSecurityGamma
  - ERTMedicalAmber
  - ERTMedicalRed
  - ERTMedicalGamma
  - ERTEngineerAmber
  - ERTEngineerRed
  - ERTEngineerGamma
  - ERTJanitorAmber
  - ERTJanitorRed
  - ERTJanitorGamma
  - DeathSquad
  - BlueShieldOfficer
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#fcdf03"
  roles:
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - CentralCommandOfficial
  - CentralCommandAdministrator
  - CentralCommandOperator
  - CentralCommandSpecialOperationsOfficer
  - CentralCommandOfficer
  - CBURNLeader
  - CBURNSierraLeader
  - CBURNAgent
  - CBURNSierraAgent
  - ERTLeaderAmber
  - ERTLeaderRed
  - ERTLeaderGamma
  - ERTSecurityAmber
  - ERTSecurityRed
  - ERTSecurityGamma
  - ERTMedicalAmber
  - ERTMedicalRed
  - ERTMedicalGamma
  - ERTEngineerAmber
  - ERTEngineerRed
  - ERTEngineerGamma
  - ERTJanitorAmber
  - ERTJanitorRed
  - ERTJanitorGamma
  - DeathSquad
  - BlueShieldOfficer
  - Magistrat
  primary: false
  weight: 100
  accountNumber: 1317 #backmen: currency

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#f2ac26"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant
  - SeniorEngineer
  accountNumber: 1318 #backmen: currency

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#57b8f0"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - SeniorPhysician
  - Coroner
  - MedicalSurgeon
  accountNumber: 1319 #backmen: currency

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#1563bd"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  - SeniorOfficer
  - SecurityPilot
  - Brigmedic
  accountNumber: 1320  #backmen: currency

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant
  - SeniorResearcher
  accountNumber: 1321  #backmen: currency

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#191e9e"
  roles:
  - Borg
  - StationAi
  - BorgSecurity

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#6ca729"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  - SecurityPilot
  primary: false
  accountNumber: 1322  #backmen: currency

- type: department
  id: Law
  name: department-Law
  description: department-Law-description
  color: "#d98b71"
  roles:
  - Magistrat
  - IAA
  - Lawyer
  accountNumber: 1323  #backmen: currency
