- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 288000 # 80 hours
    - !type:AgeRequirement
      requiredAge: 24
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Science
  wage: 75
  #end-backmen: currency

- type: startingGear
  id: SeniorResearcherGear
  equipment:
    ears: ClothingHeadsetScience
    socks: ClothingUnderwearSocksSeniorResearcher
