- type: microwaveMealRecipe
  id: RecipeLasanga
  name: lasanga recipe
  result: Lasanga
  time: 20
  solids:
    FoodTomato: 1
    FoodMeat: 1
    FoodCheeseSlice: 2
  reagents:
    Milk: 5
    Egg: 10

- type: microwaveMealRecipe
  id: RecipeNotsandwich
  name: notsandwich recipe
  result: NotSandwich
  time: 10
  solids:
    ClothingMaskItalianMoustache: 1
    FoodBreadPlainSlice: 2

- type: microwaveMealRecipe
  id: RecipeChawanmushi
  name: chawanmushi recipe
  result: Chawanmushi
  time: 15
  reagents:
    Milk: 5
    Egg: 10
    Water: 5

- type: microwaveMealRecipe # TODO: Fix
  id: RecipeBoneSoup1
  name: bone soup recipe
  result: FoodSoupBone
  time: 10
  reagents:
    Water: 10
  solids:
    FoodBowlBig: 1
    HandsAnimal: 1

- type: microwaveMealRecipe # TODO: Fix
  id: RecipeBoneSoup2
  name: bone soup recipe
  result: FoodSoupBone
  time: 10
  reagents:
    Water: 10
  solids:
    FoodBowlBig: 1
    LegsAnimal: 1

- type: microwaveMealRecipe # TODO: Fix
  id: RecipeBoneSoup3
  name: bone soup recipe
  result: FoodSoupBone
  time: 10
  reagents:
    Water: 10
  solids:
    FoodBowlBig: 1
    FeetAnimal: 1

- type: microwaveMealRecipe # TODO: Fix
  id: RecipeBoneSoup4
  name: bone soup recipe
  result: FoodSoupBone
  time: 10
  reagents:
    Water: 10
  solids:
    TorsoAnimal: 1
    FoodBowlBig: 1

- type: reaction
  id: BluespaceHot
  reactants:
    Vodka:
      amount: 3
    SpaceUp:
      amount: 3
    Licoxide:
      amount: 1
    Ice:
      amount: 3
  products:
    BluespaceHot: 10

- type: reaction
  id: Sontse
  reactants:
    WeldingFuel:
      amount: 1
    Coffee:
      amount: 1
    JuiceOrange:
      amount: 1
    Mead:
      amount: 1
  products:
    Sontse: 4

- type: reaction
  id: UplinkDrink
  reactants:
    NuclearCola:
      amount: 1
    Rum:
      amount: 1
    Iron:
      amount: 1
    WeldingFuel:
      amount: 1
  products:
    UplinkDrink: 4

- type: microwaveMealRecipe
  id: RecipeSawdustSoup
  name: sawdust soup recipe
  result: FoodSoupSawdust
  time: 20
  reagents:
    Water: 30
    Cellulose: 20
  solids:
    FoodBowlBig: 1