# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
    - !type:DepartmentTimeRequirement
      department: Silicon
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hours
    - !type:OverallPlaytimeRequirement
      time: 648000 # 180 hours
  weight: 18
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-crew
  jobEntity: StationAiBrain
  jobPreviewEntity: PlayerStationAiPreview
  applyTraits: false

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 216000 # 60 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-crew
  jobEntity: PlayerBorgBattery
  applyTraits: false
