- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: true
  objective: roles-antag-rev-head-objective
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 360000 # 100 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
  # guides: [ Revolutionaries ] # DS14: disabled due to lack of localization

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
  # guides: [ Revolutionaries ] # DS14: disabled due to lack of localization

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
