- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      # - id: ClothingHeadsetAltSecurity # DS14-disabled
      - id: ClothingHandsGlovesCombat
      # - id: ClothingShoesBootsJack # DS14-disabled
      # - id: ClothingOuterCoatWarden # DS14-disabled
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitWarden
      - id: HoloprojectorSecurity
      # - id: BookSpaceLaw # DS14-disabled
      - id: ClothingHeadHatCapWardenAlt # Corvax-SecFashion
      - id: ClothingOuterCoatWardenAlt # Corvax-SecFashion
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2
      - id: ClothingNeckBodyCamera # DS14
        amount: 4
      - id: EftposSecurity # backmen-economy
        amount: 2
      - id: Eftpos # backmen-economy
        amount: 2

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      # - id: ClothingHeadsetAltSecurity # DS14-disabled
      - id: ClothingHandsGlovesCombat
      # - id: ClothingShoesBootsJack # DS14-disabled
      # - id: ClothingOuterCoatWarden # DS14-disabled
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2
      - id: ClothingNeckBodyCamera # DS14
        amount: 4
      - id: EftposSecurity # backmen-economy
        amount: 2
      - id: Eftpos # backmen-economy
        amount: 2

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
      - id: ClothingBeltSecurityFilled
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesColorBlack
      - id: HoloprojectorSecurity
        prob: 0.6
      - id: PistolDominator # DS14
      - id: WeaponPistolMk58 # DS14
      - id: ClothingNeckBodyCamera # DS14-disabled

- type: entity
  id: LockerBrigmedicFilled
  suffix: Brigmedic, Filled
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadsetBrigmedic
      - id: TrackingImplanter
      - id: RubberStampBrigmedic
      - id: ClothingOuterHardsuitBrigmedic
      - id: ClothingHandsGlovesLatex
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpskirtOfLife
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingHeadHatBeretSecurityMedic
      - id: ClothingOuterVestArmorMedSec
      - id: ClothingOuterVestSecurityMedic
      - id: ClothingOuterCoatLabSecurityMedic
        prob: 0.1
      - id: MedkitFilled
      - id: MedkitCombatFilled
        prob: 0.4
      - id: MedkitAdvancedFilled
        prob: 0.1
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.2
      - id: MedkitToxinFilled
        prob: 0.2
      - id: MedkitBurnFilled
        prob: 0.3

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHatFedoraBrown
      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
      - id: ClothingOuterCoatDetective
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
        amount: 2
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: RubberStampDetective
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers
      - id: HandLabeler
      - id: FlippoEngravedLighter
      - id: ADTtelescopicBaton # ADT

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      # NT is cheap, what can you do...
      - id: Wirecutter
      - id: Screwdriver
      - id: Multitool
        prob: 0.75

- type: entity
  parent: [GunSafe, BaseRestrictedContraband]
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: GunSafe
  id: GunSafeDominator
  name: dominators safe
  components:
  - type: StorageFill
    contents:
    - id: PistolDominator
      amount: 3

- type: entity
  parent: [GunSafe, BaseRestrictedContraband]
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: [GunSafe, BaseRestrictedContraband]
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: [GunSafe, BaseRestrictedContraband]
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: [GunSafe, BaseRestrictedContraband]
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: [GunSafe, BaseRestrictedContraband]
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [GunSafe, BaseRestrictedContraband]
  name: wt550 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponLaserCarbine
      amount: 3

- type: entity
  id: LockerBlueShieldFilled
  suffix: BlueShield, Filled
  parent: LockerBlueShield
  components:
  - type: StorageFill
    contents:
      - id: NitrogenTankFilled
      - id: OxygenTankFilled
      - id: MedkitFilled
      - id: MedkitCombatFilled
      - id: MedkitAdvancedFilled
      - id: ClothingNeckCloakNanotrasen
      - id: ClothingEyesHudAdvanced
      - id: RubberStampBlueShield
      - id: WeaponDisabler
      - id: ClothingHeadHelmetSwat
