- type: job
  id: TypanChef
  name: job-name-typan-chef
  playTimeTracker: TypanChef
  description: Повар из далёкого космоса.
  startingGear: SyndicateChef
  icon: "JobIconTypanChef"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 6000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess

- type: startingGear
  id: SyndicateChef
  equipment:
    ears: ClothingHeadsetAltTypan
    jumpsuit: ClothingUniformJumpsuitTypanChef
    back: ClothingBackpackSyndicate
    outerClothing: ClothingOuterApronTypanChef
    shoes: ClothingShoesColorBlack
    id: SyndiPDAChef
